# Generated by Django 4.1.1 on 2022-09-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
